# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/despoina/opencv_projects/stereo_calibration

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/despoina/opencv_projects/stereo_calibration

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/despoina/opencv_projects/stereo_calibration/CMakeFiles /home/despoina/opencv_projects/stereo_calibration/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/despoina/opencv_projects/stereo_calibration/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cameraCalibrator

# Build rule for target.
cameraCalibrator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cameraCalibrator
.PHONY : cameraCalibrator

# fast build rule for target.
cameraCalibrator/fast:
	$(MAKE) -f CMakeFiles/cameraCalibrator.dir/build.make CMakeFiles/cameraCalibrator.dir/build
.PHONY : cameraCalibrator/fast

src/monocularCameraCalibrator.o: src/monocularCameraCalibrator.cpp.o
.PHONY : src/monocularCameraCalibrator.o

# target to build an object file
src/monocularCameraCalibrator.cpp.o:
	$(MAKE) -f CMakeFiles/cameraCalibrator.dir/build.make CMakeFiles/cameraCalibrator.dir/src/monocularCameraCalibrator.cpp.o
.PHONY : src/monocularCameraCalibrator.cpp.o

src/monocularCameraCalibrator.i: src/monocularCameraCalibrator.cpp.i
.PHONY : src/monocularCameraCalibrator.i

# target to preprocess a source file
src/monocularCameraCalibrator.cpp.i:
	$(MAKE) -f CMakeFiles/cameraCalibrator.dir/build.make CMakeFiles/cameraCalibrator.dir/src/monocularCameraCalibrator.cpp.i
.PHONY : src/monocularCameraCalibrator.cpp.i

src/monocularCameraCalibrator.s: src/monocularCameraCalibrator.cpp.s
.PHONY : src/monocularCameraCalibrator.s

# target to generate assembly for a file
src/monocularCameraCalibrator.cpp.s:
	$(MAKE) -f CMakeFiles/cameraCalibrator.dir/build.make CMakeFiles/cameraCalibrator.dir/src/monocularCameraCalibrator.cpp.s
.PHONY : src/monocularCameraCalibrator.cpp.s

src/stereoCameraCalibrator.o: src/stereoCameraCalibrator.cpp.o
.PHONY : src/stereoCameraCalibrator.o

# target to build an object file
src/stereoCameraCalibrator.cpp.o:
	$(MAKE) -f CMakeFiles/cameraCalibrator.dir/build.make CMakeFiles/cameraCalibrator.dir/src/stereoCameraCalibrator.cpp.o
.PHONY : src/stereoCameraCalibrator.cpp.o

src/stereoCameraCalibrator.i: src/stereoCameraCalibrator.cpp.i
.PHONY : src/stereoCameraCalibrator.i

# target to preprocess a source file
src/stereoCameraCalibrator.cpp.i:
	$(MAKE) -f CMakeFiles/cameraCalibrator.dir/build.make CMakeFiles/cameraCalibrator.dir/src/stereoCameraCalibrator.cpp.i
.PHONY : src/stereoCameraCalibrator.cpp.i

src/stereoCameraCalibrator.s: src/stereoCameraCalibrator.cpp.s
.PHONY : src/stereoCameraCalibrator.s

# target to generate assembly for a file
src/stereoCameraCalibrator.cpp.s:
	$(MAKE) -f CMakeFiles/cameraCalibrator.dir/build.make CMakeFiles/cameraCalibrator.dir/src/stereoCameraCalibrator.cpp.s
.PHONY : src/stereoCameraCalibrator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cameraCalibrator"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/monocularCameraCalibrator.o"
	@echo "... src/monocularCameraCalibrator.i"
	@echo "... src/monocularCameraCalibrator.s"
	@echo "... src/stereoCameraCalibrator.o"
	@echo "... src/stereoCameraCalibrator.i"
	@echo "... src/stereoCameraCalibrator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

